### ISSUE TITLE
Undefined names: 'sampling' and '_required'

### ISSUE THREAD

**Issue by cclauss** [google/ffn#13]
[flake8](http://flake8.pycqa.org) testing of https://github.com/google/ffn on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./ffn/inference/resegmentation_analysis.py:256:7: F821 undefined name 'sampling'
      sampling, result.eval.from_a)
      ^
./ffn/inference/resegmentation_analysis.py:259:7: F821 undefined name 'sampling'
      sampling, result.eval.from_b)
      ^
./ffn/utils/bounding_box.py:374:17: F821 undefined name '_required'
          yield _required(self.start_to_box((x, y, z)))
                ^
./ffn/utils/bounding_box.py:395:11: F821 undefined name '_required'
          _required(self.index_to_sub_box(i)) for i in range(i_begin, i_end))
          ^
4     F821 undefined name 'sampling'
4
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by Griffbo99** [comment]
Hey, did you ever solve this issue? I'm having the same issue with '_required' not being defined. Thanks!

**Comment by cclauss** [comment]
Nope.

**Comment by mjanusz** [comment]
Just pushed a fix, sorry about that!
