### ISSUE TITLE
Realignment and Irregular section substitution

### ISSUE THREAD

**Issue by 0xJustin** [google/ffn#34]
In the paper "Automated Reconstruction of a Serial-Section EM Drosophila Brain with Flood-Filling Networks and Local Realignment" there is mention of a local realignment and an irregular section substitution step before FFN is run. Is that code available somewhere? I couldn't find it in this repository

**Comment by chinasaur** [comment]
Sorry, that code isn't fully released. There are hooks for plugging in different alignment methods in this repo, in [align.py](https://github.com/google/ffn/blob/master/ffn/inference/align.py). But the translation-only alignment and irregular section substitution used in that paper I haven't plugged in there yet.

**Comment by 0xJustin** [comment]
I'm working on a similar problem on anisotropic EM, and I would be curious to see how you implemented those steps. If you had preliminary code you could share, even if it is messy or unfinished it would be very helpful to me! I've been trying all sorts of feature / template matching strategies but still am having trouble getting an approach that abstracts well... My email is in my profile if you want to chat. Thanks!

**Comment by mjanusz** [comment]
One thing that is also worth mentioning is that we now have an open source alignment system which is known to work even on challenging EM data (https://github.com/google-research/sofima). If your current data is suffering from non-trivial alignment issues, this might be an overall easier solution.

**Comment by 0xJustin** [comment]
Thank you for bringing that code base to my attention! I had started on an optical flow implementation, and this must have slipped through the cracks. I'll take a look :)
